name: WWE API CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flake8 dvc scikit-learn fastapi uvicorn

    - name: Lint code
      run: |
        flake8 . || true

    - name: Run tests
      run: |
        pytest -v

    - name: Check DVC data (optional)
      run: |
        if [ -f dvc.yaml ]; then
          dvc pull
        else
          echo "No DVC data found, skipping..."
        fi
